L_fmmm_options <- list("useHighLevelOptions"=TRUE,
                       "singleLevel"=TRUE,
                       "pageFormat"="square",
                       "unitEdgeLength"=100.0,
                       "newInitialPlacement"=FALSE,

                       "randSeed"=100L,
                       "edgeLengthMeasurement"="boundingcircle",
                       "allowedPositions"="integer",
                       "maxIntPosExponent"=40L,

                       "pageRatio"=1.0,
                       "stepsForRotatingComponents"=10L,
                       "tipOverCCs"="nogrowingrow",
                       "minDistCC"=100.0,
                       "presortCCs"="decreasingheight",

                       "minGraphSize"=50L,
                       "galaxyChoice"="nonuniformproblowermass",
                       "randomTries"=20L,
                       "maxIterChange"="linearlydecreasing",
                       "maxIterFactor"=10L,
                       "initialPlacementMult"="advanced",

                       "forceModel"="new",
                       "springStrength"=1.0,
                       "repForcesStrength"=1.0,
                       "repulsiveForcesCalculation"="nmm",
                       "stopCriterion"="fixediterationsorthreshold",
                       "threshold"=0.01,
                       "fixedIterations"=30L,
                       "forceScalingFactor"=0.05,
                       "coolTemperature"=FALSE,
                       "coolValue"=0.99,
                       "initialPlacementForces"="randomranditernr",

                       "resizeDrawing"=TRUE,
                       "resizingScalar"=1.0,
                       "fineTuningIterations"=20L,
                       "fineTuneScalar"=0.2,
                       "adjustPostRepStrengthDynamically"=TRUE,
                       "postSpringStrength"=20.0,
                       "postStrengthOfRepForces"=0.01,

                       "frGridQuotient"=2L,
                       "nmTreeConstruction"="subtreebysubtree",
                       "nmSmallCell"="iteratively",
                       "nmParticlesInLeaves"=25L,
                       "nmPrecision"=4L
                       )