// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rogdf_version
IntegerVector rogdf_version();
RcppExport SEXP OGDF_rogdf_version() {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        IntegerVector __result = rogdf_version();
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rogdf_circular_layout
NumericMatrix rogdf_circular_layout(GraphAttributes graph, double minDistCircle = 20, double minDistLevel = 20, double minDistSibling = 10, double minDistCC = 20, double pageRatio = 1);
RcppExport SEXP OGDF_rogdf_circular_layout(SEXP graphSEXP, SEXP minDistCircleSEXP, SEXP minDistLevelSEXP, SEXP minDistSiblingSEXP, SEXP minDistCCSEXP, SEXP pageRatioSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< GraphAttributes >::type graph(graphSEXP );
        Rcpp::traits::input_parameter< double >::type minDistCircle(minDistCircleSEXP );
        Rcpp::traits::input_parameter< double >::type minDistLevel(minDistLevelSEXP );
        Rcpp::traits::input_parameter< double >::type minDistSibling(minDistSiblingSEXP );
        Rcpp::traits::input_parameter< double >::type minDistCC(minDistCCSEXP );
        Rcpp::traits::input_parameter< double >::type pageRatio(pageRatioSEXP );
        NumericMatrix __result = rogdf_circular_layout(graph, minDistCircle, minDistLevel, minDistSibling, minDistCC, pageRatio);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rogdf_tree_layout
NumericMatrix rogdf_tree_layout(GraphAttributes graph, double siblingDistance = 20, double subtreeDistance = 20, double levelDistance = 50, double treeDistance = 50, bool orthogonalLayout = false, Orientation orientation = topToBottom, TreeLayout::RootSelectionType selectRoot = TreeLayout::rootIsSource);
RcppExport SEXP OGDF_rogdf_tree_layout(SEXP graphSEXP, SEXP siblingDistanceSEXP, SEXP subtreeDistanceSEXP, SEXP levelDistanceSEXP, SEXP treeDistanceSEXP, SEXP orthogonalLayoutSEXP, SEXP orientationSEXP, SEXP selectRootSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< GraphAttributes >::type graph(graphSEXP );
        Rcpp::traits::input_parameter< double >::type siblingDistance(siblingDistanceSEXP );
        Rcpp::traits::input_parameter< double >::type subtreeDistance(subtreeDistanceSEXP );
        Rcpp::traits::input_parameter< double >::type levelDistance(levelDistanceSEXP );
        Rcpp::traits::input_parameter< double >::type treeDistance(treeDistanceSEXP );
        Rcpp::traits::input_parameter< bool >::type orthogonalLayout(orthogonalLayoutSEXP );
        Rcpp::traits::input_parameter< Orientation >::type orientation(orientationSEXP );
        Rcpp::traits::input_parameter< TreeLayout::RootSelectionType >::type selectRoot(selectRootSEXP );
        NumericMatrix __result = rogdf_tree_layout(graph, siblingDistance, subtreeDistance, levelDistance, treeDistance, orthogonalLayout, orientation, selectRoot);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rogdf_fmmm_layout
NumericMatrix rogdf_fmmm_layout(GraphAttributes graph, ROGDF_FMMM_Options options = ROGDF_FMMM_Options()  				/* @R L_fmmm_options */);
RcppExport SEXP OGDF_rogdf_fmmm_layout(SEXP graphSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< GraphAttributes >::type graph(graphSEXP );
        Rcpp::traits::input_parameter< ROGDF_FMMM_Options >::type options(optionsSEXP );
        NumericMatrix __result = rogdf_fmmm_layout(graph, options);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
